; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

; --- OTA upload via IP (ArduinoOTA / espota) ---
; First upload MUST be via USB once.
; Then you can set:
; upload_protocol = espota
; upload_port = 192.168.2.176
; upload_flags =
;   --port=3232
;   --auth=
; If you set OTA_PASSWORD in code, put it after --auth=

lib_deps =
  bblanchon/ArduinoJson@^7.0.4
  links2004/WebSockets@^2.6.1
  ayushsharma82/ElegantOTA@^3.1.5

build_flags =
  -DCORE_DEBUG_LEVEL=0
